version: '2'
services:
  jack-app:
    image: jack
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://jack-postgresql:5432/jack
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
      - SPRING_DATA_JEST_URI=http://jack-elasticsearch:9200
      - SPRING_ELASTICSEARCH_REST_URIS=http://jack-elasticsearch:9200
    ports:
      - 8080:8080
  jack-postgresql:
    extends:
      file: postgresql.yml
      service: jack-postgresql
  jack-elasticsearch:
    extends:
      file: elasticsearch.yml
      service: jack-elasticsearch
